permalink: pretty
theme: jekyll_patternbot
patternbot:
  title: "Leashed"
  description: |
    A local website that carries all your pets apperal needs. Carrying a variety of different leashes, collars, bandanas and more. The wesbite displays this in a minimilistic manner.
  font_url: "https://fonts.googleapis.com/css?family=Noto+Sans+JP:300,400,700&display=swap"
  colors:
    background: "--color-primary-light"
    accent: "--color-primary-dark"
    patterns:
      brand.logos: "--color-secondary"
      brand.typefaces: "--color-primary"
      brand.colors: "--color-primary"
      icons.icons: "--color-secondary"
  rationales:
    typefaces.primary: |
      Primary is white because there won't be many colours used, trying to keep the website a combination of whites and greys for a more modern/minimilist vibe.
    colors.primary: |
      This colour was selected for mainly for the header nav and the footer. Mainly being used for background elements. The light is used for fonts that need to be reversed out and the black is for most of the type on the website.
    colors.secondary: |
      This colour was selected to be used in some/most buttons on the website.
    accent: |
      This is used maily for buttons.
    accent.secondary: |
      This color was selected for cards in the product list page.
